language: python
sudo: false
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install:
    - travis_retry pip install tox
script:
    - tox
notifications:
    email: false
